version: '3'

services:
  web:
    build: .
    command: bash -c "python ./gentelella/manage.py migrate && python ./gentelella/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
